import{a as g,S as y,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const b="48224339-eb859193739eff8149475b5bf",L="https://pixabay.com/api/",S=async(t,o=1,s=15)=>{const a={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s},{data:e}=await g.get(L,{params:a});return e},v=t=>t.map(({webformatURL:o,largeImageURL:s,tags:a,likes:e,views:r,comments:i,downloads:f})=>`
      <a href="${s}" class="gallery-item">
        <img src="${o}" alt="${a}" loading="lazy" />
        <div class="info">
          <p><b>Likes:</b> ${e}</p>
          <p><b>Views:</b> ${r}</p>
          <p><b>Comments:</b> ${i}</p>
          <p><b>Downloads:</b> ${f}</p>
        </div>
      </a>
    `).join(""),w=(t,o)=>{t.insertAdjacentHTML("beforeend",o),new y(".gallery a").refresh()},F=document.querySelector("#search-form"),m=document.querySelector(".gallery"),d=document.querySelector(".load-more"),h=document.querySelector(".loader");let l="",c=1;const q=()=>h.classList.remove("hidden"),u=()=>h.classList.add("hidden"),E=async t=>{if(t.preventDefault(),l=t.currentTarget.elements.searchQuery.value.trim(),!l){n.error({title:"Error",message:"Please enter a search term.",position:"topRight",backgroundColor:"#FF0000"});return}m.innerHTML="",d.classList.add("hidden"),c=1,await p()},p=async()=>{q();try{const t=await S(l,c);if(u(),t.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query.",position:"topRight",backgroundColor:"#FF0000"});return}const o=v(t.hits);w(m,o),t.totalHits>c*15?d.classList.remove("hidden"):n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#FF0000"})}catch(t){u(),n.error({title:"Error",message:t.message,position:"topRight",backgroundColor:"#FF0000"})}},R=async()=>{c+=1,await p();const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})};F.addEventListener("submit",E);d.addEventListener("click",R);
//# sourceMappingURL=index.js.map
